Seoul1ro/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers

from main import views
from main.views import SendtoAIView, ShowResult

router = routers.DefaultRouter()

# router.register('', views.SendtoAIView, 'main')
# input = SendtoAIView.as_view({
#     'post': 'create',
# })
#
# list = SendtoAIView.as_view({
#     'get': 'list',
# })

urlpatterns = [
    path('', ShowResult),
    # path('', include(router.urls)),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models


class Search(models.Model):
    # 축척 입력칸
    scale = models.IntegerField()
    # 원하는 이용 면적 입력 칸
    area = models.IntegerField()
    # 이미지 넣는 칸
    Image = models.ImageField(upload_to="input")     # BASE_DIR/media/input 에 저장

main/forms.py
from django import forms

from main.models import Search


class InputForm(forms.ModelForm):
    class Meta:
        model = Search
        fields = '__all__'

main/views.py
import argparse

from django.shortcuts import render
from rest_framework import viewsets, status
from rest_framework.response import Response
from rest_framework.views import APIView
from PIL import Image

from AI.tile_predict import tile_predict
from main.forms import InputForm
from main.models import Search
from main.serializers import SearchSerializer


def ShowResult(request):
    if request.method == 'POST':
        form = InputForm(request.POST, request.FILES)
        if form.is_valid():
            data = form.save()
            image = Image.open(data.Image)
            width, height = image.size

            origin = str(data.Image)
            path = str(data.Image).split('.')[0]
            # AI 돌려서 result 얻기
            result = tile_predict("unet_min", [width,height,3], "E:\\JXS\\Seoul1ro\\AI\\unet_mini300_06_07_20.hdf5", "media/"+origin, "tiff", "media/output/", 3, 8)
            print(type(result))
            img = Image.open(result)
            print(img)
            name = result.split('.')[0]
            print(name)
            img = img.convert('RGB')
            img.save(name+'.jpg', 'JPEG')
            # result = Search.objects.last()
            # result = data.Image
            return render(request, 'main/index.html', {
                'form': form,
                'result': name+'.jpg',
            })
        else:
            # 올바른 파일 올려달라고 메세지 넣기
            form = InputForm()
            return render(request, 'main/index.html', {
                'form': form,
            })

    # GET
    else:
        form = InputForm()
        return render(request, 'main/index.html', {
            'form': form,
        })


class SendtoAIView(viewsets.ModelViewSet):
    serializer_class = SearchSerializer
    queryset = Search.objects.all()

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        self.perform_create(serializer)
        headers = self.get_success_headers(serializer.data)
        return Response(serializer.data, status=status.HTTP_201_CREATED, headers=headers)

    def list(self, request, *args, **kwargs):
        queryset = self.filter_queryset(self.get_queryset())

        page = self.paginate_queryset(queryset)
        if page is not None:
            serializer = self.get_serializer(page, many=True)
            return self.get_paginated_response(serializer.data)

        serializer = self.get_serializer(queryset, many=True)
        return Response(serializer.data)

main/templates/main/edit.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="static/css/recommed.css" />
    <style>
      @import url("https://fonts.googleapis.com/css2?family=Montserrat:wght@200;300;400;500;600;700;800;900&display=swap");
    </style>
    <title>Seoul1ro team website</title>
  </head>

  <body>
    <div class="container">
      <div class="content">
        <h1 class="title">
          <img class="bg" src="static/img/cut_bg.png" />
          <br />
          <span class="title__">Recommend</span>
          <img class="pin" src="static/img/pin.png" />
        </h1>
        <div class="view__container">
          <div class="view__road">
            <div class="view__road__text">Road Only</div>
            <div>
              <img class="view__road__img" src="static/img/road_only.jpeg" />
            </div>
          </div>
          <div class="view__all">
            <div class="view__all__text">
              You have selected<span class="view_all_figure">Scale</span
              ><span class="view_all_figure">Area</span>
              <div class="view_all_box">
                <img class="view__all__img" src="static/img/image (1).png" />
              </div>
              <span class="view__all__idx">Dimension:0000</span>
              <span class="view__all__idx">Buildings:0000</span>
            </div>
          </div>
          <div class="view__building">
            <div class="view__building__text">Building Only</div>
            <div>
              <img
                class="view__building__img"
                src="static/img/road_only.jpeg"
              />
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

main/templates/main/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="../static/css/index.css" />
    <style>
      @import url("https://fonts.googleapis.com/css2?family=Montserrat:wght@200;300;400;500;600;700;800;900&display=swap");
    </style>
    <title>Seoul1ro team website</title>
  </head>

  <body>
    <div class="container">
      <div class="content">
        <h1 class="title">
          <img class="bg" src="../static/img/top_bg.png" />
          <img class="logo" src="../static/img/Junctionxseoul-white-ver1.svg" />
          <br />
          <span class="title__">Fire</span
          ><span span="" class="title__">where</span>
        </h1>
        <div class="content__form">
          <div class="img">
            <h5 class="img__text">Fill the form out</h5>
            <div class="img__box">
              <form action="" method="post" enctype="multipart/form-data">
                <input type="hidden" />
                <p>
                  <label for="id_scale">Scale</label>
                  <input type="number" name="scale" required="" id="id_scale" />
                </p>
                <p>
                  <label for="id_area">Area</label>
                  <input type="number" name="area" required="" id="id_area" />
                </p>
                <p>
                  <label for="id_Image">Image</label>
                  <input
                    type="file"
                    name="Image"
                    accept="image/*"
                    required=""
                    id="id_Image"
                  />
                </p>
              </form>
            </div>
            <button class="button">Submit</button>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>